config/routes.rb
Rails.application.routes.draw do
  # ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストログイン機能の設定
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: "public" do
    root :to => "homes#top"
    get "about" => "homes#about"
    resources :registrations, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]

    get 'users/my_page' => "users#show"
    get 'users/information/edit' => "users#edit"
    patch 'users/information' => "users#update"
    get 'users/unsubscribe' => "users#unsubscribe"
    patch 'users/withdraw' => "users#withdraw"
    get 'users/favorites' => 'users#favorites'

    resources :contributions, only: [:new, :index, :show, :edit, :update, :destroy] do
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
    end

    post "contributions" => "contributions#create"
    get "contributions" => "contributions#search"
    resources :comments, only: [:create, :update, :edit, :destroy]
    patch "comments" => "commentss#update"
  end

  namespace :admin do
    root "homes#top"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :comments, only: [:index, :update, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contributions, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_contributions, through: :favorites, source: :contribution
  has_many :comments  #User.commentsで、ユーザーの所有するコメントを取得

   validates :name, presence: true
   validates :email, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_root_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-xl-8 mx-auto">
      <h2 class="mb-4">
        <%= @user.name %>さんの詳細情報編集
      </h2>
      <%= form_with model: @user, url: admin_user_path, local:true do |f| %>
        <div class="form-group row">
          <%= f.label :id, "ユーザーID", class: "form-label col-sm-4" %>
          <div class="col-sm-8">
            <%= f.label :id, @user.id %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :name, "氏名", class: "form-label col-sm-4" %>
          <div class="col-sm-4">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, "メールアドレス", class: "form-label col-sm-4" %>
          <div class="col-sm-4">
            <%= f.email_field :email, class: "form-control" %>
          </div>
        </div>


        <div class="form-group row">
          <%= f.label :is_deleted, "ユーザーステータス", class: "form-label col-sm-4" %>
          <div class="col-sm-8">
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_deleted, false, class: "form-check-input" %>
              <%= f.label :is_deleted, "有効", value: false, class: "form-check-label" %>
            </div>
            <div class="form-check form-check-inline">
              <%= f.radio_button :is_deleted, true, class: "form-check-input" %>
              <%= f.label :is_deleted, "退会", class: "form-check-label" %>
            </div>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-4"></div>
          <div class="col-sm-8">
            <%= f.submit "変更を保存", class: "btn btn-success" %>
          </div>
        </div>
      <% end %>

      <table class="table table-bordered">
        <tr>
          <th class="table-active">削除</th>
          <th class="table-active" style = "width:20%" >タイトル</th>
          <th class="table-active" style = "width:65%" >コメント</th>
        </tr>
        <% @user.comments.each do |comment| %>
        <tr>
          <td><%= link_to "削除", admin_comment_path(comment), method: :delete, class: "btn btn-danger" %></td>
          <td><%= comment.contribution.title %></td>
          <td><%= comment.text %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-xl-8 mx-auto">
      <h2 class="mb-4">
        <%= @user.name %>さんの詳細情報
      </h2>

      <table class="table table-borderless">
        <tr>
          <th style="width:25%">ユーザーID</th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th>ユーザー名</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>投稿名・コメント</th>
          <td>
            <% @user.comments.each do |comment| %>
              <%= comment.contribution.title %>・
              <%= comment.text %><br>
            <% end %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td>
            <%= link_to "編集する", edit_admin_user_path(@user), class:"btn btn-success" %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>