config/routes.rb
Rails.application.routes.draw do
  # ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  #ゲストログイン機能の設定
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: "public" do
    root :to => "homes#top"
    get "about" => "homes#about"
    resources :registrations, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]

    get 'users/my_page' => "users#show"
    get 'users/information/edit' => "users#edit"
    patch 'users/information' => "users#update"
    get 'users/unsubscribe' => "users#unsubscribe"
    patch 'users/withdraw' => "users#withdraw"
    get 'users/favorites' => 'users#favorites'

    resources :contributions, only: [:new, :index, :show, :edit, :update, :destroy] do
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
    end

    post "contributions" => "contributions#create"
    get "contributions" => "contributions#search"
    resources :comments, only: [:create, :update, :edit, :destroy]
    patch "comments" => "commentss#update"
  end

  namespace :admin do
    root "homes#top"
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :comments, only: [:index, :update, :destroy]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user  #Comment.userでコメントの所有者を取得
  belongs_to :contribution  #Comment.contributionでそのコメントがされた投稿を取得

  validates :text, presence: true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  has_one_attached :video
  validates :title, length: { in: 1..100 }

  belongs_to :user
  #Contribution.commentsで、投稿が所有するコメントを取得
  has_many :comments, dependent: :destroy

  #contributionテーブルから中間テーブルに対する関連付け
  has_many :contribution_tag_relations, dependent: :destroy
  #contributionテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :contribution_tag_relations, dependent: :destroy

  has_many :favorites, dependent: :destroy

  def self.search_by_word(word)
    Contribution.where(['title LIKE ? OR text LIKE ?', "%#{word}%", "%#{word}%"])
  end

  #タイトルが存在しているかを確認するバリデーション
  validates :title, presence: true
  #内容が存在しているかを確認するバリデーション
  validates :text, presence: true
  #動画が存在しているかを確認するバリデーション
  validates :video, presence: true

  

  #ユーザidがFavoritesテーブル内に存在するかどうか
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/contribution_tag_relation.rb
class ContributionTagRelation < ApplicationRecord
  belongs_to :contribution
  belongs_to :tag
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :contribution
end

app/models/tag.rb
class Tag < ApplicationRecord
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :contribution_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :contributions, through: :contribution_tag_relations, dependent: :destroy

  #タグが存在しているかを確認するバリデーション
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contributions, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_contributions, through: :favorites, source: :contribution
  has_many :comments  #User.commentsで、ユーザーの所有するコメントを取得

   validates :name, presence: true
   validates :email, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def create
  end

  def destroy
    comment = Comment.find(params[:id])
    user = comment.user
    comment.destroy
    redirect_to admin_user_path(user)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @users = User.all
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(resource)
      admin_root_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_root_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<!-- adminのheader -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container">
    <%= link_to contributions_path, class: "navbar-brand" do %>
      <span>Technology-sharing</span>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン(ユーザー側)", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン(管理者側)", new_admin_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_public_header.html.erb
<!-- publicのheader -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container">
    <%= link_to contributions_path, class: "navbar-brand" do %>
      <span>Technology-sharing</span>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "マイページ", users_my_page_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "投稿する", new_contribution_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechnologySharing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header style="z-index: 10 !important; position: relative;">
      <% if request.fullpath.include? "/admin" %>
        <%= render "layouts/admin_header" %>
      <% else %>
        <%= render "layouts/public_header" %>
      <% end %>
    </header>

    <%= yield %>

    <footer style="width: 100%">
      <div>
        <div class="bg-light border-top py-3">
          <div class="container">
            <div class="row">
              <div class="col-sm-9 mb-2">
                <span class="text-muted">Copyright © Technology-sharing All Rights Reserved.</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>